syntax = "proto3";

package engine;

option go_package = "github.com/webitel/protos/engine";

import "google/api/annotations.proto";
import "team_chat_tag.proto";

service AgentChatTagService {
  rpc SearchAgentChatTag (SearchAgentChatTagRequest) returns (ListChatTag) {
    option (google.api.http) = {
      get: "/call_center/agents/chat_tags"
    };
  }
}

message SearchAgentChatTagRequest {
  int32 page = 1;
  int32 size = 2;
  string q = 3;

  string sort = 4;
  repeated string fields = 5;

  repeated uint32 id = 6;
}
