// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outbound_resource.proto

package engine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteOutboundResourceDisplayRequest struct {
	ResourceId           int64    `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOutboundResourceDisplayRequest) Reset()         { *m = DeleteOutboundResourceDisplayRequest{} }
func (m *DeleteOutboundResourceDisplayRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOutboundResourceDisplayRequest) ProtoMessage()    {}
func (*DeleteOutboundResourceDisplayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{0}
}

func (m *DeleteOutboundResourceDisplayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOutboundResourceDisplayRequest.Unmarshal(m, b)
}
func (m *DeleteOutboundResourceDisplayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOutboundResourceDisplayRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOutboundResourceDisplayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOutboundResourceDisplayRequest.Merge(m, src)
}
func (m *DeleteOutboundResourceDisplayRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOutboundResourceDisplayRequest.Size(m)
}
func (m *DeleteOutboundResourceDisplayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOutboundResourceDisplayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOutboundResourceDisplayRequest proto.InternalMessageInfo

func (m *DeleteOutboundResourceDisplayRequest) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *DeleteOutboundResourceDisplayRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteOutboundResourceDisplayRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type UpdateOutboundResourceDisplayRequest struct {
	ResourceId           int64    `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Display              string   `protobuf:"bytes,3,opt,name=display,proto3" json:"display,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOutboundResourceDisplayRequest) Reset()         { *m = UpdateOutboundResourceDisplayRequest{} }
func (m *UpdateOutboundResourceDisplayRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOutboundResourceDisplayRequest) ProtoMessage()    {}
func (*UpdateOutboundResourceDisplayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{1}
}

func (m *UpdateOutboundResourceDisplayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOutboundResourceDisplayRequest.Unmarshal(m, b)
}
func (m *UpdateOutboundResourceDisplayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOutboundResourceDisplayRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOutboundResourceDisplayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOutboundResourceDisplayRequest.Merge(m, src)
}
func (m *UpdateOutboundResourceDisplayRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOutboundResourceDisplayRequest.Size(m)
}
func (m *UpdateOutboundResourceDisplayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOutboundResourceDisplayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOutboundResourceDisplayRequest proto.InternalMessageInfo

func (m *UpdateOutboundResourceDisplayRequest) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *UpdateOutboundResourceDisplayRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateOutboundResourceDisplayRequest) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *UpdateOutboundResourceDisplayRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadOutboundResourceDisplayRequest struct {
	ResourceId           int64    `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOutboundResourceDisplayRequest) Reset()         { *m = ReadOutboundResourceDisplayRequest{} }
func (m *ReadOutboundResourceDisplayRequest) String() string { return proto.CompactTextString(m) }
func (*ReadOutboundResourceDisplayRequest) ProtoMessage()    {}
func (*ReadOutboundResourceDisplayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{2}
}

func (m *ReadOutboundResourceDisplayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOutboundResourceDisplayRequest.Unmarshal(m, b)
}
func (m *ReadOutboundResourceDisplayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOutboundResourceDisplayRequest.Marshal(b, m, deterministic)
}
func (m *ReadOutboundResourceDisplayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOutboundResourceDisplayRequest.Merge(m, src)
}
func (m *ReadOutboundResourceDisplayRequest) XXX_Size() int {
	return xxx_messageInfo_ReadOutboundResourceDisplayRequest.Size(m)
}
func (m *ReadOutboundResourceDisplayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOutboundResourceDisplayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOutboundResourceDisplayRequest proto.InternalMessageInfo

func (m *ReadOutboundResourceDisplayRequest) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *ReadOutboundResourceDisplayRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadOutboundResourceDisplayRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchOutboundResourceDisplayRequest struct {
	ResourceId           int64    `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	Sort                 string   `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields               []string `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	Id                   []uint32 `protobuf:"varint,7,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchOutboundResourceDisplayRequest) Reset()         { *m = SearchOutboundResourceDisplayRequest{} }
func (m *SearchOutboundResourceDisplayRequest) String() string { return proto.CompactTextString(m) }
func (*SearchOutboundResourceDisplayRequest) ProtoMessage()    {}
func (*SearchOutboundResourceDisplayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{3}
}

func (m *SearchOutboundResourceDisplayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOutboundResourceDisplayRequest.Unmarshal(m, b)
}
func (m *SearchOutboundResourceDisplayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOutboundResourceDisplayRequest.Marshal(b, m, deterministic)
}
func (m *SearchOutboundResourceDisplayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOutboundResourceDisplayRequest.Merge(m, src)
}
func (m *SearchOutboundResourceDisplayRequest) XXX_Size() int {
	return xxx_messageInfo_SearchOutboundResourceDisplayRequest.Size(m)
}
func (m *SearchOutboundResourceDisplayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOutboundResourceDisplayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOutboundResourceDisplayRequest proto.InternalMessageInfo

func (m *SearchOutboundResourceDisplayRequest) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *SearchOutboundResourceDisplayRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchOutboundResourceDisplayRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchOutboundResourceDisplayRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchOutboundResourceDisplayRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchOutboundResourceDisplayRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SearchOutboundResourceDisplayRequest) GetId() []uint32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListOutboundResourceDisplay struct {
	Next                 bool               `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*ResourceDisplay `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListOutboundResourceDisplay) Reset()         { *m = ListOutboundResourceDisplay{} }
func (m *ListOutboundResourceDisplay) String() string { return proto.CompactTextString(m) }
func (*ListOutboundResourceDisplay) ProtoMessage()    {}
func (*ListOutboundResourceDisplay) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{4}
}

func (m *ListOutboundResourceDisplay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOutboundResourceDisplay.Unmarshal(m, b)
}
func (m *ListOutboundResourceDisplay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOutboundResourceDisplay.Marshal(b, m, deterministic)
}
func (m *ListOutboundResourceDisplay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOutboundResourceDisplay.Merge(m, src)
}
func (m *ListOutboundResourceDisplay) XXX_Size() int {
	return xxx_messageInfo_ListOutboundResourceDisplay.Size(m)
}
func (m *ListOutboundResourceDisplay) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOutboundResourceDisplay.DiscardUnknown(m)
}

var xxx_messageInfo_ListOutboundResourceDisplay proto.InternalMessageInfo

func (m *ListOutboundResourceDisplay) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListOutboundResourceDisplay) GetItems() []*ResourceDisplay {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateOutboundResourceDisplayRequest struct {
	ResourceId           int64    `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Display              string   `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOutboundResourceDisplayRequest) Reset()         { *m = CreateOutboundResourceDisplayRequest{} }
func (m *CreateOutboundResourceDisplayRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOutboundResourceDisplayRequest) ProtoMessage()    {}
func (*CreateOutboundResourceDisplayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{5}
}

func (m *CreateOutboundResourceDisplayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOutboundResourceDisplayRequest.Unmarshal(m, b)
}
func (m *CreateOutboundResourceDisplayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOutboundResourceDisplayRequest.Marshal(b, m, deterministic)
}
func (m *CreateOutboundResourceDisplayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOutboundResourceDisplayRequest.Merge(m, src)
}
func (m *CreateOutboundResourceDisplayRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOutboundResourceDisplayRequest.Size(m)
}
func (m *CreateOutboundResourceDisplayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOutboundResourceDisplayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOutboundResourceDisplayRequest proto.InternalMessageInfo

func (m *CreateOutboundResourceDisplayRequest) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *CreateOutboundResourceDisplayRequest) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *CreateOutboundResourceDisplayRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ResourceDisplay struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Display              string   `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceDisplay) Reset()         { *m = ResourceDisplay{} }
func (m *ResourceDisplay) String() string { return proto.CompactTextString(m) }
func (*ResourceDisplay) ProtoMessage()    {}
func (*ResourceDisplay) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{6}
}

func (m *ResourceDisplay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceDisplay.Unmarshal(m, b)
}
func (m *ResourceDisplay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceDisplay.Marshal(b, m, deterministic)
}
func (m *ResourceDisplay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDisplay.Merge(m, src)
}
func (m *ResourceDisplay) XXX_Size() int {
	return xxx_messageInfo_ResourceDisplay.Size(m)
}
func (m *ResourceDisplay) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDisplay.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDisplay proto.InternalMessageInfo

func (m *ResourceDisplay) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResourceDisplay) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

type DeleteOutboundResourceRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOutboundResourceRequest) Reset()         { *m = DeleteOutboundResourceRequest{} }
func (m *DeleteOutboundResourceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOutboundResourceRequest) ProtoMessage()    {}
func (*DeleteOutboundResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{7}
}

func (m *DeleteOutboundResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOutboundResourceRequest.Unmarshal(m, b)
}
func (m *DeleteOutboundResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOutboundResourceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOutboundResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOutboundResourceRequest.Merge(m, src)
}
func (m *DeleteOutboundResourceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOutboundResourceRequest.Size(m)
}
func (m *DeleteOutboundResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOutboundResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOutboundResourceRequest proto.InternalMessageInfo

func (m *DeleteOutboundResourceRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteOutboundResourceRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadOutboundResourceRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOutboundResourceRequest) Reset()         { *m = ReadOutboundResourceRequest{} }
func (m *ReadOutboundResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadOutboundResourceRequest) ProtoMessage()    {}
func (*ReadOutboundResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{8}
}

func (m *ReadOutboundResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOutboundResourceRequest.Unmarshal(m, b)
}
func (m *ReadOutboundResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOutboundResourceRequest.Marshal(b, m, deterministic)
}
func (m *ReadOutboundResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOutboundResourceRequest.Merge(m, src)
}
func (m *ReadOutboundResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadOutboundResourceRequest.Size(m)
}
func (m *ReadOutboundResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOutboundResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOutboundResourceRequest proto.InternalMessageInfo

func (m *ReadOutboundResourceRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadOutboundResourceRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchOutboundResourceRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields               []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Id                   []uint32 `protobuf:"varint,6,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchOutboundResourceRequest) Reset()         { *m = SearchOutboundResourceRequest{} }
func (m *SearchOutboundResourceRequest) String() string { return proto.CompactTextString(m) }
func (*SearchOutboundResourceRequest) ProtoMessage()    {}
func (*SearchOutboundResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{9}
}

func (m *SearchOutboundResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOutboundResourceRequest.Unmarshal(m, b)
}
func (m *SearchOutboundResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOutboundResourceRequest.Marshal(b, m, deterministic)
}
func (m *SearchOutboundResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOutboundResourceRequest.Merge(m, src)
}
func (m *SearchOutboundResourceRequest) XXX_Size() int {
	return xxx_messageInfo_SearchOutboundResourceRequest.Size(m)
}
func (m *SearchOutboundResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOutboundResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOutboundResourceRequest proto.InternalMessageInfo

func (m *SearchOutboundResourceRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchOutboundResourceRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchOutboundResourceRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchOutboundResourceRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchOutboundResourceRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SearchOutboundResourceRequest) GetId() []uint32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type PatchOutboundResourceRequest struct {
	Id                    int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit                 int32             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Enabled               bool              `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rps                   int32             `protobuf:"varint,4,opt,name=rps,proto3" json:"rps,omitempty"`
	Reserve               bool              `protobuf:"varint,5,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Variables             map[string]string `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Number                string            `protobuf:"bytes,7,opt,name=number,proto3" json:"number,omitempty"`
	MaxSuccessivelyErrors int32             `protobuf:"varint,8,opt,name=max_successively_errors,json=maxSuccessivelyErrors,proto3" json:"max_successively_errors,omitempty"`
	Name                  string            `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	ErrorIds              []string          `protobuf:"bytes,10,rep,name=error_ids,json=errorIds,proto3" json:"error_ids,omitempty"`
	Fields                []string          `protobuf:"bytes,11,rep,name=fields,proto3" json:"fields,omitempty"`
	Gateway               *Lookup           `protobuf:"bytes,12,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Description           string            `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Patterns              []string          `protobuf:"bytes,14,rep,name=patterns,proto3" json:"patterns,omitempty"`
	FailureDialDelay      uint32            `protobuf:"varint,15,opt,name=failure_dial_delay,json=failureDialDelay,proto3" json:"failure_dial_delay,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *PatchOutboundResourceRequest) Reset()         { *m = PatchOutboundResourceRequest{} }
func (m *PatchOutboundResourceRequest) String() string { return proto.CompactTextString(m) }
func (*PatchOutboundResourceRequest) ProtoMessage()    {}
func (*PatchOutboundResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{10}
}

func (m *PatchOutboundResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchOutboundResourceRequest.Unmarshal(m, b)
}
func (m *PatchOutboundResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchOutboundResourceRequest.Marshal(b, m, deterministic)
}
func (m *PatchOutboundResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchOutboundResourceRequest.Merge(m, src)
}
func (m *PatchOutboundResourceRequest) XXX_Size() int {
	return xxx_messageInfo_PatchOutboundResourceRequest.Size(m)
}
func (m *PatchOutboundResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchOutboundResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchOutboundResourceRequest proto.InternalMessageInfo

func (m *PatchOutboundResourceRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PatchOutboundResourceRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PatchOutboundResourceRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *PatchOutboundResourceRequest) GetRps() int32 {
	if m != nil {
		return m.Rps
	}
	return 0
}

func (m *PatchOutboundResourceRequest) GetReserve() bool {
	if m != nil {
		return m.Reserve
	}
	return false
}

func (m *PatchOutboundResourceRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *PatchOutboundResourceRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PatchOutboundResourceRequest) GetMaxSuccessivelyErrors() int32 {
	if m != nil {
		return m.MaxSuccessivelyErrors
	}
	return 0
}

func (m *PatchOutboundResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PatchOutboundResourceRequest) GetErrorIds() []string {
	if m != nil {
		return m.ErrorIds
	}
	return nil
}

func (m *PatchOutboundResourceRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *PatchOutboundResourceRequest) GetGateway() *Lookup {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *PatchOutboundResourceRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PatchOutboundResourceRequest) GetPatterns() []string {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *PatchOutboundResourceRequest) GetFailureDialDelay() uint32 {
	if m != nil {
		return m.FailureDialDelay
	}
	return 0
}

type UpdateOutboundResourceRequest struct {
	Id                    int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit                 int32             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Enabled               bool              `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rps                   int32             `protobuf:"varint,4,opt,name=rps,proto3" json:"rps,omitempty"`
	Reserve               bool              `protobuf:"varint,5,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Variables             map[string]string `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Number                string            `protobuf:"bytes,7,opt,name=number,proto3" json:"number,omitempty"`
	MaxSuccessivelyErrors int32             `protobuf:"varint,8,opt,name=max_successively_errors,json=maxSuccessivelyErrors,proto3" json:"max_successively_errors,omitempty"`
	Name                  string            `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	ErrorIds              []string          `protobuf:"bytes,12,rep,name=error_ids,json=errorIds,proto3" json:"error_ids,omitempty"`
	Gateway               *Lookup           `protobuf:"bytes,13,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Description           string            `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Patterns              []string          `protobuf:"bytes,15,rep,name=patterns,proto3" json:"patterns,omitempty"`
	FailureDialDelay      uint32            `protobuf:"varint,16,opt,name=failure_dial_delay,json=failureDialDelay,proto3" json:"failure_dial_delay,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *UpdateOutboundResourceRequest) Reset()         { *m = UpdateOutboundResourceRequest{} }
func (m *UpdateOutboundResourceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOutboundResourceRequest) ProtoMessage()    {}
func (*UpdateOutboundResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{11}
}

func (m *UpdateOutboundResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOutboundResourceRequest.Unmarshal(m, b)
}
func (m *UpdateOutboundResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOutboundResourceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOutboundResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOutboundResourceRequest.Merge(m, src)
}
func (m *UpdateOutboundResourceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOutboundResourceRequest.Size(m)
}
func (m *UpdateOutboundResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOutboundResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOutboundResourceRequest proto.InternalMessageInfo

func (m *UpdateOutboundResourceRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateOutboundResourceRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UpdateOutboundResourceRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *UpdateOutboundResourceRequest) GetRps() int32 {
	if m != nil {
		return m.Rps
	}
	return 0
}

func (m *UpdateOutboundResourceRequest) GetReserve() bool {
	if m != nil {
		return m.Reserve
	}
	return false
}

func (m *UpdateOutboundResourceRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *UpdateOutboundResourceRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *UpdateOutboundResourceRequest) GetMaxSuccessivelyErrors() int32 {
	if m != nil {
		return m.MaxSuccessivelyErrors
	}
	return 0
}

func (m *UpdateOutboundResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateOutboundResourceRequest) GetErrorIds() []string {
	if m != nil {
		return m.ErrorIds
	}
	return nil
}

func (m *UpdateOutboundResourceRequest) GetGateway() *Lookup {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *UpdateOutboundResourceRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateOutboundResourceRequest) GetPatterns() []string {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *UpdateOutboundResourceRequest) GetFailureDialDelay() uint32 {
	if m != nil {
		return m.FailureDialDelay
	}
	return 0
}

type CreateOutboundResourceRequest struct {
	Limit                 int32             `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Enabled               bool              `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rps                   int32             `protobuf:"varint,3,opt,name=rps,proto3" json:"rps,omitempty"`
	Reserve               bool              `protobuf:"varint,4,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Variables             map[string]string `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Number                string            `protobuf:"bytes,6,opt,name=number,proto3" json:"number,omitempty"`
	MaxSuccessivelyErrors int32             `protobuf:"varint,7,opt,name=max_successively_errors,json=maxSuccessivelyErrors,proto3" json:"max_successively_errors,omitempty"`
	Name                  string            `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	ErrorIds              []string          `protobuf:"bytes,9,rep,name=error_ids,json=errorIds,proto3" json:"error_ids,omitempty"`
	Gateway               *Lookup           `protobuf:"bytes,10,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Description           string            `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Patterns              []string          `protobuf:"bytes,12,rep,name=patterns,proto3" json:"patterns,omitempty"`
	FailureDialDelay      uint32            `protobuf:"varint,13,opt,name=failure_dial_delay,json=failureDialDelay,proto3" json:"failure_dial_delay,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *CreateOutboundResourceRequest) Reset()         { *m = CreateOutboundResourceRequest{} }
func (m *CreateOutboundResourceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOutboundResourceRequest) ProtoMessage()    {}
func (*CreateOutboundResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{12}
}

func (m *CreateOutboundResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOutboundResourceRequest.Unmarshal(m, b)
}
func (m *CreateOutboundResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOutboundResourceRequest.Marshal(b, m, deterministic)
}
func (m *CreateOutboundResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOutboundResourceRequest.Merge(m, src)
}
func (m *CreateOutboundResourceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOutboundResourceRequest.Size(m)
}
func (m *CreateOutboundResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOutboundResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOutboundResourceRequest proto.InternalMessageInfo

func (m *CreateOutboundResourceRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CreateOutboundResourceRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CreateOutboundResourceRequest) GetRps() int32 {
	if m != nil {
		return m.Rps
	}
	return 0
}

func (m *CreateOutboundResourceRequest) GetReserve() bool {
	if m != nil {
		return m.Reserve
	}
	return false
}

func (m *CreateOutboundResourceRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *CreateOutboundResourceRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *CreateOutboundResourceRequest) GetMaxSuccessivelyErrors() int32 {
	if m != nil {
		return m.MaxSuccessivelyErrors
	}
	return 0
}

func (m *CreateOutboundResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOutboundResourceRequest) GetErrorIds() []string {
	if m != nil {
		return m.ErrorIds
	}
	return nil
}

func (m *CreateOutboundResourceRequest) GetGateway() *Lookup {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *CreateOutboundResourceRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateOutboundResourceRequest) GetPatterns() []string {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *CreateOutboundResourceRequest) GetFailureDialDelay() uint32 {
	if m != nil {
		return m.FailureDialDelay
	}
	return 0
}

type OutboundResource struct {
	Id                    int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId              int64             `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	CreatedAt             int64             `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy             *Lookup           `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt             int64             `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy             *Lookup           `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Limit                 int32             `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Enabled               bool              `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rps                   int32             `protobuf:"varint,9,opt,name=rps,proto3" json:"rps,omitempty"`
	Reserve               bool              `protobuf:"varint,10,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Variables             map[string]string `protobuf:"bytes,11,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Number                string            `protobuf:"bytes,12,opt,name=number,proto3" json:"number,omitempty"`
	MaxSuccessivelyErrors int32             `protobuf:"varint,13,opt,name=max_successively_errors,json=maxSuccessivelyErrors,proto3" json:"max_successively_errors,omitempty"`
	Name                  string            `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	ErrorIds              []string          `protobuf:"bytes,15,rep,name=error_ids,json=errorIds,proto3" json:"error_ids,omitempty"`
	LastErrorId           string            `protobuf:"bytes,16,opt,name=last_error_id,json=lastErrorId,proto3" json:"last_error_id,omitempty"`
	SuccessivelyErrors    int32             `protobuf:"varint,17,opt,name=successively_errors,json=successivelyErrors,proto3" json:"successively_errors,omitempty"`
	LastErrorAt           int64             `protobuf:"varint,18,opt,name=last_error_at,json=lastErrorAt,proto3" json:"last_error_at,omitempty"`
	Gateway               *Lookup           `protobuf:"bytes,19,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Description           string            `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	Patterns              []string          `protobuf:"bytes,21,rep,name=patterns,proto3" json:"patterns,omitempty"`
	FailureDialDelay      uint32            `protobuf:"varint,22,opt,name=failure_dial_delay,json=failureDialDelay,proto3" json:"failure_dial_delay,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *OutboundResource) Reset()         { *m = OutboundResource{} }
func (m *OutboundResource) String() string { return proto.CompactTextString(m) }
func (*OutboundResource) ProtoMessage()    {}
func (*OutboundResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{13}
}

func (m *OutboundResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboundResource.Unmarshal(m, b)
}
func (m *OutboundResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboundResource.Marshal(b, m, deterministic)
}
func (m *OutboundResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboundResource.Merge(m, src)
}
func (m *OutboundResource) XXX_Size() int {
	return xxx_messageInfo_OutboundResource.Size(m)
}
func (m *OutboundResource) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboundResource.DiscardUnknown(m)
}

var xxx_messageInfo_OutboundResource proto.InternalMessageInfo

func (m *OutboundResource) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OutboundResource) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *OutboundResource) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *OutboundResource) GetCreatedBy() *Lookup {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *OutboundResource) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *OutboundResource) GetUpdatedBy() *Lookup {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

func (m *OutboundResource) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *OutboundResource) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *OutboundResource) GetRps() int32 {
	if m != nil {
		return m.Rps
	}
	return 0
}

func (m *OutboundResource) GetReserve() bool {
	if m != nil {
		return m.Reserve
	}
	return false
}

func (m *OutboundResource) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *OutboundResource) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *OutboundResource) GetMaxSuccessivelyErrors() int32 {
	if m != nil {
		return m.MaxSuccessivelyErrors
	}
	return 0
}

func (m *OutboundResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OutboundResource) GetErrorIds() []string {
	if m != nil {
		return m.ErrorIds
	}
	return nil
}

func (m *OutboundResource) GetLastErrorId() string {
	if m != nil {
		return m.LastErrorId
	}
	return ""
}

func (m *OutboundResource) GetSuccessivelyErrors() int32 {
	if m != nil {
		return m.SuccessivelyErrors
	}
	return 0
}

func (m *OutboundResource) GetLastErrorAt() int64 {
	if m != nil {
		return m.LastErrorAt
	}
	return 0
}

func (m *OutboundResource) GetGateway() *Lookup {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *OutboundResource) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OutboundResource) GetPatterns() []string {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *OutboundResource) GetFailureDialDelay() uint32 {
	if m != nil {
		return m.FailureDialDelay
	}
	return 0
}

type ListOutboundResource struct {
	Next                 bool                `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*OutboundResource `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListOutboundResource) Reset()         { *m = ListOutboundResource{} }
func (m *ListOutboundResource) String() string { return proto.CompactTextString(m) }
func (*ListOutboundResource) ProtoMessage()    {}
func (*ListOutboundResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_c866ec047a06af0d, []int{14}
}

func (m *ListOutboundResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOutboundResource.Unmarshal(m, b)
}
func (m *ListOutboundResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOutboundResource.Marshal(b, m, deterministic)
}
func (m *ListOutboundResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOutboundResource.Merge(m, src)
}
func (m *ListOutboundResource) XXX_Size() int {
	return xxx_messageInfo_ListOutboundResource.Size(m)
}
func (m *ListOutboundResource) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOutboundResource.DiscardUnknown(m)
}

var xxx_messageInfo_ListOutboundResource proto.InternalMessageInfo

func (m *ListOutboundResource) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListOutboundResource) GetItems() []*OutboundResource {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteOutboundResourceDisplayRequest)(nil), "engine.DeleteOutboundResourceDisplayRequest")
	proto.RegisterType((*UpdateOutboundResourceDisplayRequest)(nil), "engine.UpdateOutboundResourceDisplayRequest")
	proto.RegisterType((*ReadOutboundResourceDisplayRequest)(nil), "engine.ReadOutboundResourceDisplayRequest")
	proto.RegisterType((*SearchOutboundResourceDisplayRequest)(nil), "engine.SearchOutboundResourceDisplayRequest")
	proto.RegisterType((*ListOutboundResourceDisplay)(nil), "engine.ListOutboundResourceDisplay")
	proto.RegisterType((*CreateOutboundResourceDisplayRequest)(nil), "engine.CreateOutboundResourceDisplayRequest")
	proto.RegisterType((*ResourceDisplay)(nil), "engine.ResourceDisplay")
	proto.RegisterType((*DeleteOutboundResourceRequest)(nil), "engine.DeleteOutboundResourceRequest")
	proto.RegisterType((*ReadOutboundResourceRequest)(nil), "engine.ReadOutboundResourceRequest")
	proto.RegisterType((*SearchOutboundResourceRequest)(nil), "engine.SearchOutboundResourceRequest")
	proto.RegisterType((*PatchOutboundResourceRequest)(nil), "engine.PatchOutboundResourceRequest")
	proto.RegisterMapType((map[string]string)(nil), "engine.PatchOutboundResourceRequest.VariablesEntry")
	proto.RegisterType((*UpdateOutboundResourceRequest)(nil), "engine.UpdateOutboundResourceRequest")
	proto.RegisterMapType((map[string]string)(nil), "engine.UpdateOutboundResourceRequest.VariablesEntry")
	proto.RegisterType((*CreateOutboundResourceRequest)(nil), "engine.CreateOutboundResourceRequest")
	proto.RegisterMapType((map[string]string)(nil), "engine.CreateOutboundResourceRequest.VariablesEntry")
	proto.RegisterType((*OutboundResource)(nil), "engine.OutboundResource")
	proto.RegisterMapType((map[string]string)(nil), "engine.OutboundResource.VariablesEntry")
	proto.RegisterType((*ListOutboundResource)(nil), "engine.ListOutboundResource")
}

func init() { proto.RegisterFile("outbound_resource.proto", fileDescriptor_c866ec047a06af0d) }

var fileDescriptor_c866ec047a06af0d = []byte{
	// 1314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x98, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0xc7, 0xe5, 0xfc, 0xcf, 0xc9, 0x9f, 0xf6, 0x37, 0xdb, 0x4d, 0xad, 0x74, 0xf3, 0x23, 0xb8,
	0x05, 0xa2, 0xaa, 0x24, 0xda, 0x76, 0xb5, 0xc0, 0xb2, 0x37, 0x5b, 0xda, 0x8b, 0xa2, 0x4a, 0x80,
	0x2b, 0xb8, 0xd8, 0x9b, 0x30, 0x89, 0x67, 0xb3, 0xa3, 0x75, 0xec, 0xd4, 0x9e, 0x74, 0x9b, 0x85,
	0x2e, 0x82, 0x07, 0x40, 0x42, 0x5c, 0x23, 0x84, 0xb4, 0x17, 0x3c, 0x00, 0x37, 0xbc, 0x02, 0x42,
	0xe2, 0x82, 0x57, 0xe0, 0x41, 0x90, 0xc7, 0x9e, 0x26, 0x71, 0xc6, 0xae, 0x03, 0x5b, 0xe0, 0x6e,
	0xfe, 0xf9, 0xcc, 0x77, 0xce, 0xf9, 0x1c, 0x7b, 0x8e, 0x61, 0xdd, 0x1e, 0xb3, 0x9e, 0x3d, 0xb6,
	0x8c, 0xae, 0x43, 0x5c, 0x7b, 0xec, 0xf4, 0x49, 0x7b, 0xe4, 0xd8, 0xcc, 0x46, 0x39, 0x62, 0x0d,
	0xa8, 0x45, 0xea, 0xa5, 0xbe, 0x6d, 0xb9, 0xcc, 0x1f, 0xac, 0xdf, 0x1a, 0xd8, 0xf6, 0xc0, 0x24,
	0x1d, 0x3c, 0xa2, 0x1d, 0x6c, 0x59, 0x36, 0xc3, 0x8c, 0xda, 0x96, 0xeb, 0xcf, 0x6a, 0x0c, 0xb6,
	0x0e, 0x88, 0x49, 0x18, 0xf9, 0x20, 0xb0, 0xa9, 0x07, 0x26, 0x0f, 0xa8, 0x3b, 0x32, 0xf1, 0x44,
	0x27, 0xa7, 0x63, 0xe2, 0x32, 0xf4, 0x0a, 0x94, 0xc4, 0x66, 0x5d, 0x6a, 0xa8, 0x4a, 0x53, 0x69,
	0xa5, 0x75, 0x10, 0x43, 0x47, 0x06, 0xaa, 0x42, 0x8a, 0x1a, 0x6a, 0x8a, 0x8f, 0xa7, 0xa8, 0x81,
	0x36, 0xa0, 0x68, 0xd8, 0x43, 0x4c, 0x2d, 0x6f, 0x79, 0x9a, 0x0f, 0x17, 0xfc, 0x81, 0x23, 0x43,
	0xfb, 0x5a, 0x81, 0xad, 0x8f, 0x47, 0x06, 0x7e, 0xf9, 0xdb, 0xaa, 0x90, 0x37, 0x7c, 0x13, 0x7c,
	0xd3, 0xa2, 0x2e, 0xba, 0xf3, 0x82, 0x32, 0x21, 0x41, 0x0e, 0x68, 0x3a, 0xc1, 0xc6, 0x3f, 0xea,
	0x84, 0x9f, 0x15, 0xd8, 0x3a, 0x21, 0xd8, 0xe9, 0x3f, 0xfe, 0xbb, 0xdb, 0x22, 0xc8, 0x8c, 0xf0,
	0x80, 0xf0, 0x8d, 0xb3, 0x3a, 0x6f, 0x7b, 0x63, 0x2e, 0x7d, 0x46, 0xf8, 0xae, 0x59, 0x9d, 0xb7,
	0x51, 0x19, 0x94, 0x53, 0x7e, 0xf4, 0xa2, 0xae, 0x9c, 0xf2, 0x15, 0xb6, 0xc3, 0xd4, 0x2c, 0x1f,
	0xe0, 0x6d, 0x54, 0x83, 0xdc, 0x23, 0x4a, 0x4c, 0xc3, 0x55, 0x73, 0xcd, 0x74, 0xab, 0xa8, 0x07,
	0xbd, 0xe0, 0x60, 0xf9, 0x66, 0xba, 0x55, 0xf1, 0x0e, 0xa6, 0x7d, 0x0a, 0x1b, 0xc7, 0xd4, 0x65,
	0x11, 0xc2, 0x3d, 0xd3, 0x16, 0x39, 0x67, 0x5c, 0x6a, 0x41, 0xe7, 0x6d, 0xf4, 0x26, 0x64, 0x29,
	0x23, 0x43, 0x57, 0x4d, 0x35, 0xd3, 0xad, 0xd2, 0xee, 0x7a, 0xdb, 0x87, 0xb5, 0x1d, 0x3e, 0xb4,
	0xbf, 0x4a, 0x7b, 0x0e, 0x5b, 0xef, 0x39, 0xe4, 0x25, 0x10, 0x32, 0x43, 0x44, 0x2a, 0x86, 0x88,
	0x70, 0x74, 0xde, 0x85, 0x95, 0xf0, 0xa9, 0x7c, 0x27, 0x28, 0x32, 0xd6, 0xe6, 0x2d, 0x6b, 0xc7,
	0xd0, 0x90, 0x67, 0x95, 0x50, 0x1d, 0x36, 0x35, 0x27, 0x25, 0x15, 0x92, 0xf2, 0x3e, 0x6c, 0xc8,
	0xe0, 0xfc, 0x4b, 0xb6, 0xbe, 0x51, 0xa0, 0x21, 0x87, 0x4e, 0x98, 0x13, 0x30, 0x29, 0x12, 0x98,
	0x52, 0x61, 0x98, 0xd2, 0x61, 0x98, 0x32, 0x52, 0x98, 0xb2, 0x12, 0x98, 0x72, 0x97, 0x30, 0xfd,
	0x92, 0x81, 0x5b, 0x1f, 0x62, 0x16, 0x2d, 0x29, 0x7c, 0xc2, 0x35, 0xc8, 0x9a, 0x74, 0x48, 0x59,
	0xa0, 0xc7, 0xef, 0x78, 0xe1, 0x20, 0x16, 0xee, 0x99, 0xc4, 0x0f, 0x66, 0x41, 0x17, 0x5d, 0xb4,
	0x0a, 0x69, 0x67, 0xe4, 0x72, 0x6d, 0x59, 0xdd, 0x6b, 0x7a, 0x6b, 0x1d, 0xe2, 0x12, 0xe7, 0x8c,
	0x70, 0xfc, 0x0b, 0xba, 0xe8, 0xa2, 0x8f, 0xa0, 0x78, 0x86, 0x1d, 0xea, 0x3d, 0xe8, 0x27, 0x41,
	0x69, 0x77, 0x4f, 0xa0, 0x1a, 0x27, 0xb2, 0xfd, 0x89, 0x78, 0xea, 0xd0, 0x62, 0xce, 0x44, 0x9f,
	0x5a, 0xf1, 0xfc, 0x60, 0x8d, 0x87, 0x3d, 0xe2, 0xa8, 0x79, 0xee, 0x9d, 0xa0, 0x87, 0xee, 0xc2,
	0xfa, 0x10, 0x9f, 0x77, 0xdd, 0x71, 0xbf, 0x4f, 0x5c, 0x97, 0x9e, 0x11, 0x73, 0xd2, 0x25, 0x8e,
	0x63, 0x3b, 0xae, 0x5a, 0xe0, 0x52, 0x6f, 0x0e, 0xf1, 0xf9, 0xc9, 0xcc, 0xec, 0x21, 0x9f, 0xe4,
	0xd9, 0x85, 0x87, 0x44, 0x2d, 0xfa, 0xbe, 0xf6, 0xda, 0x5e, 0xd0, 0xf9, 0xa3, 0x5d, 0x6a, 0xb8,
	0x2a, 0x70, 0x77, 0x17, 0xf8, 0xc0, 0x91, 0xe1, 0xce, 0x04, 0xa2, 0x34, 0x17, 0x88, 0x16, 0xe4,
	0x07, 0x98, 0x91, 0xa7, 0x78, 0xa2, 0x96, 0x9b, 0x4a, 0xab, 0xb4, 0x5b, 0x15, 0x27, 0x3d, 0xb6,
	0xed, 0x27, 0xe3, 0x91, 0x2e, 0xa6, 0x51, 0x13, 0x4a, 0x06, 0x71, 0xfb, 0x0e, 0x1d, 0x79, 0x1f,
	0x0f, 0xb5, 0xc2, 0x77, 0x9e, 0x1d, 0x42, 0x75, 0x28, 0x8c, 0x30, 0x63, 0xc4, 0xb1, 0x5c, 0xb5,
	0xea, 0xef, 0x2f, 0xfa, 0x68, 0x07, 0xd0, 0x23, 0x4c, 0xcd, 0xb1, 0x43, 0xba, 0x06, 0xc5, 0x66,
	0xd7, 0x20, 0x5e, 0xce, 0xac, 0x34, 0x95, 0x56, 0x45, 0x5f, 0x0d, 0x66, 0x0e, 0x28, 0x36, 0x0f,
	0xbc, 0xf1, 0xfa, 0x7d, 0xa8, 0xce, 0xfb, 0xd2, 0x8b, 0xdf, 0x13, 0x32, 0xe1, 0x00, 0x14, 0x75,
	0xaf, 0xe9, 0x11, 0x70, 0x86, 0xcd, 0x31, 0x09, 0x12, 0xcf, 0xef, 0xdc, 0x4b, 0xbd, 0xad, 0x68,
	0x3f, 0x65, 0xa0, 0x21, 0xff, 0xb4, 0xfc, 0x1b, 0x34, 0xe9, 0x8b, 0x34, 0xdd, 0x11, 0x3e, 0x8e,
	0x55, 0xf9, 0x5f, 0xc2, 0xa9, 0x1c, 0xc2, 0x69, 0x06, 0x9b, 0xca, 0x52, 0xd8, 0x54, 0xe3, 0xb1,
	0x59, 0x49, 0x84, 0xcd, 0xea, 0xb5, 0x60, 0xf3, 0x22, 0x03, 0x0d, 0xf9, 0xf7, 0x46, 0x60, 0x73,
	0x89, 0x89, 0x12, 0x81, 0x49, 0x4a, 0x8a, 0x49, 0x5a, 0x8a, 0x49, 0x26, 0x06, 0x93, 0xec, 0x3c,
	0x26, 0xb1, 0xaa, 0x12, 0x61, 0x92, 0x4b, 0x8a, 0x49, 0x3e, 0x09, 0x26, 0x85, 0x28, 0x4c, 0x8a,
	0xd1, 0x98, 0xc0, 0x52, 0x98, 0x94, 0xe2, 0x31, 0x29, 0x27, 0xc2, 0xa4, 0x72, 0x2d, 0x98, 0xfc,
	0x9a, 0x83, 0xd5, 0x70, 0x28, 0x96, 0xfa, 0x00, 0xa3, 0x06, 0x40, 0x9f, 0x47, 0xd4, 0xe8, 0x62,
	0x16, 0xdc, 0x3a, 0x8a, 0xc1, 0xc8, 0x03, 0xef, 0x96, 0x74, 0x39, 0xdd, 0x9b, 0x70, 0x4c, 0x16,
	0xfd, 0x26, 0x96, 0xef, 0x4f, 0x3c, 0x6b, 0x63, 0xfe, 0x1a, 0xe1, 0xd6, 0xb2, 0xbe, 0xb5, 0x60,
	0xc4, 0xb7, 0x26, 0xa6, 0x7b, 0x13, 0xce, 0x81, 0xc4, 0x5a, 0xb0, 0x62, 0x7f, 0x32, 0x45, 0x3c,
	0x1f, 0x81, 0x78, 0x41, 0x8a, 0x78, 0x51, 0x8a, 0x38, 0xcc, 0x23, 0x7e, 0x38, 0x8b, 0x78, 0x89,
	0x23, 0xfe, 0x86, 0x50, 0x12, 0xf6, 0x68, 0x22, 0xaa, 0xcb, 0x49, 0xa9, 0xae, 0x24, 0xa1, 0xba,
	0x1a, 0x45, 0xf5, 0x4a, 0x88, 0x6a, 0x0d, 0x2a, 0x26, 0x76, 0x59, 0x57, 0xac, 0xe0, 0xef, 0xa3,
	0xa2, 0x5e, 0xf2, 0x06, 0x0f, 0xfd, 0x45, 0xa8, 0x03, 0x37, 0x64, 0x42, 0xfe, 0xc7, 0x85, 0x20,
	0x77, 0x51, 0xc5, 0xbc, 0x51, 0xcc, 0x54, 0xc4, 0x23, 0x39, 0x35, 0xfa, 0x80, 0xcd, 0xa6, 0xd3,
	0x8d, 0xa5, 0xd2, 0x69, 0x2d, 0x3e, 0x9d, 0x6e, 0x26, 0x4a, 0xa7, 0xda, 0xb5, 0xa4, 0xd3, 0x43,
	0x58, 0x93, 0x95, 0x11, 0xd2, 0xfa, 0xa1, 0x3d, 0x5f, 0x3f, 0xa8, 0x51, 0xf0, 0x04, 0x05, 0xc4,
	0xee, 0x6f, 0x65, 0x58, 0x0f, 0xcf, 0x9d, 0x10, 0xe7, 0x8c, 0xf6, 0x09, 0xfa, 0x1c, 0x6a, 0xf2,
	0xd7, 0x2a, 0x7a, 0x2d, 0xd1, 0x6b, 0xb7, 0x1e, 0xb9, 0xbb, 0xf6, 0xea, 0x57, 0xbf, 0xff, 0xf1,
	0x6d, 0x6a, 0x43, 0xab, 0x75, 0xfa, 0xd8, 0x34, 0xbb, 0x7d, 0x62, 0x31, 0xe2, 0x74, 0x44, 0x3d,
	0xe2, 0xde, 0x53, 0xb6, 0xd1, 0x05, 0xd4, 0xe4, 0x57, 0xf0, 0xe9, 0xee, 0xb1, 0x57, 0xf4, 0xfa,
	0xad, 0xcb, 0xc8, 0x4b, 0x9c, 0xa7, 0xfd, 0x9f, 0x2b, 0x50, 0x51, 0x84, 0x02, 0xf4, 0x0c, 0xd6,
	0x64, 0xe5, 0x04, 0xda, 0x9c, 0x56, 0x64, 0x91, 0xc5, 0x46, 0xcc, 0xc1, 0x37, 0xf9, 0xb6, 0x0d,
	0xb4, 0x21, 0xdf, 0xb6, 0xf3, 0x19, 0x35, 0x2e, 0xd0, 0x97, 0x0a, 0xd4, 0xe4, 0xf7, 0x9e, 0xe9,
	0xd9, 0x63, 0xef, 0x45, 0x31, 0x02, 0x5e, 0xe7, 0x02, 0x9a, 0xf5, 0x38, 0x01, 0x9e, 0xfb, 0xbf,
	0x80, 0x9b, 0xd2, 0x8b, 0x3c, 0xda, 0x4a, 0x72, 0xcf, 0xbf, 0x5a, 0xc0, 0xee, 0x55, 0x02, 0x9e,
	0x43, 0x4d, 0x5e, 0x1d, 0x4e, 0x7d, 0x10, 0x5b, 0x3d, 0x5e, 0x1d, 0x84, 0xed, 0xd8, 0x20, 0x7c,
	0xaf, 0x44, 0xdd, 0x75, 0x44, 0xa5, 0xbb, 0x13, 0x9f, 0x05, 0xf3, 0x25, 0x78, 0x3d, 0xaa, 0x94,
	0xd7, 0xde, 0xe2, 0x6a, 0x6e, 0x6b, 0x3b, 0x51, 0x6a, 0x66, 0x2a, 0xf7, 0x8b, 0x4e, 0x50, 0x3c,
	0x7b, 0x1e, 0xfa, 0x31, 0xb2, 0x4a, 0x5d, 0x50, 0x98, 0xe4, 0x0f, 0x4a, 0x7d, 0x33, 0x2e, 0x61,
	0x84, 0xda, 0x3b, 0x5c, 0x6d, 0x1b, 0x2d, 0xa5, 0x16, 0x7d, 0xa7, 0xc8, 0xab, 0x73, 0x21, 0x74,
	0x3b, 0x2e, 0xab, 0x92, 0x3a, 0xf2, 0x1d, 0x2e, 0x6d, 0x0f, 0xdd, 0x5e, 0x46, 0x9a, 0x1f, 0xec,
	0x17, 0x4a, 0x54, 0x3d, 0xb4, 0xe0, 0xca, 0x24, 0x7f, 0xe4, 0xa2, 0x35, 0xde, 0xe7, 0x1a, 0xef,
	0xd6, 0x97, 0xd7, 0xe8, 0x45, 0xfc, 0x07, 0x25, 0xea, 0x97, 0xc9, 0x82, 0xcc, 0x24, 0xff, 0x2b,
	0xaf, 0x74, 0xe5, 0xf6, 0xf2, 0x32, 0xf7, 0xb5, 0x87, 0xcd, 0x01, 0x65, 0x8f, 0xc7, 0xbd, 0x76,
	0xdf, 0x1e, 0x76, 0x9e, 0x92, 0x1e, 0x65, 0xc4, 0xec, 0xf0, 0xff, 0xa8, 0x6e, 0xc7, 0xdf, 0xae,
	0x97, 0xe3, 0xdd, 0xbd, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x81, 0xf2, 0xdc, 0xa4, 0x15,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OutboundResourceServiceClient is the client API for OutboundResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OutboundResourceServiceClient interface {
	// Create OutboundResource
	CreateOutboundResource(ctx context.Context, in *CreateOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error)
	// List of OutboundResource
	SearchOutboundResource(ctx context.Context, in *SearchOutboundResourceRequest, opts ...grpc.CallOption) (*ListOutboundResource, error)
	// OutboundResource item
	ReadOutboundResource(ctx context.Context, in *ReadOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error)
	// Update OutboundResource
	UpdateOutboundResource(ctx context.Context, in *UpdateOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error)
	// Patch OutboundResource
	PatchOutboundResource(ctx context.Context, in *PatchOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error)
	// Remove OutboundResource
	DeleteOutboundResource(ctx context.Context, in *DeleteOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error)
	// Create CreateOutboundResourceDisplay
	CreateOutboundResourceDisplay(ctx context.Context, in *CreateOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error)
	// List of ResourceDisplay
	SearchOutboundResourceDisplay(ctx context.Context, in *SearchOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ListOutboundResourceDisplay, error)
	// ResourceDisplay item
	ReadOutboundResourceDisplay(ctx context.Context, in *ReadOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error)
	// Update ResourceDisplay
	UpdateOutboundResourceDisplay(ctx context.Context, in *UpdateOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error)
	// Remove ResourceDisplay
	DeleteOutboundResourceDisplay(ctx context.Context, in *DeleteOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error)
}

type outboundResourceServiceClient struct {
	cc *grpc.ClientConn
}

func NewOutboundResourceServiceClient(cc *grpc.ClientConn) OutboundResourceServiceClient {
	return &outboundResourceServiceClient{cc}
}

func (c *outboundResourceServiceClient) CreateOutboundResource(ctx context.Context, in *CreateOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error) {
	out := new(OutboundResource)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/CreateOutboundResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) SearchOutboundResource(ctx context.Context, in *SearchOutboundResourceRequest, opts ...grpc.CallOption) (*ListOutboundResource, error) {
	out := new(ListOutboundResource)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/SearchOutboundResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) ReadOutboundResource(ctx context.Context, in *ReadOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error) {
	out := new(OutboundResource)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/ReadOutboundResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) UpdateOutboundResource(ctx context.Context, in *UpdateOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error) {
	out := new(OutboundResource)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/UpdateOutboundResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) PatchOutboundResource(ctx context.Context, in *PatchOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error) {
	out := new(OutboundResource)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/PatchOutboundResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) DeleteOutboundResource(ctx context.Context, in *DeleteOutboundResourceRequest, opts ...grpc.CallOption) (*OutboundResource, error) {
	out := new(OutboundResource)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/DeleteOutboundResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) CreateOutboundResourceDisplay(ctx context.Context, in *CreateOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error) {
	out := new(ResourceDisplay)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/CreateOutboundResourceDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) SearchOutboundResourceDisplay(ctx context.Context, in *SearchOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ListOutboundResourceDisplay, error) {
	out := new(ListOutboundResourceDisplay)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/SearchOutboundResourceDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) ReadOutboundResourceDisplay(ctx context.Context, in *ReadOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error) {
	out := new(ResourceDisplay)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/ReadOutboundResourceDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) UpdateOutboundResourceDisplay(ctx context.Context, in *UpdateOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error) {
	out := new(ResourceDisplay)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/UpdateOutboundResourceDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboundResourceServiceClient) DeleteOutboundResourceDisplay(ctx context.Context, in *DeleteOutboundResourceDisplayRequest, opts ...grpc.CallOption) (*ResourceDisplay, error) {
	out := new(ResourceDisplay)
	err := c.cc.Invoke(ctx, "/engine.OutboundResourceService/DeleteOutboundResourceDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutboundResourceServiceServer is the server API for OutboundResourceService service.
type OutboundResourceServiceServer interface {
	// Create OutboundResource
	CreateOutboundResource(context.Context, *CreateOutboundResourceRequest) (*OutboundResource, error)
	// List of OutboundResource
	SearchOutboundResource(context.Context, *SearchOutboundResourceRequest) (*ListOutboundResource, error)
	// OutboundResource item
	ReadOutboundResource(context.Context, *ReadOutboundResourceRequest) (*OutboundResource, error)
	// Update OutboundResource
	UpdateOutboundResource(context.Context, *UpdateOutboundResourceRequest) (*OutboundResource, error)
	// Patch OutboundResource
	PatchOutboundResource(context.Context, *PatchOutboundResourceRequest) (*OutboundResource, error)
	// Remove OutboundResource
	DeleteOutboundResource(context.Context, *DeleteOutboundResourceRequest) (*OutboundResource, error)
	// Create CreateOutboundResourceDisplay
	CreateOutboundResourceDisplay(context.Context, *CreateOutboundResourceDisplayRequest) (*ResourceDisplay, error)
	// List of ResourceDisplay
	SearchOutboundResourceDisplay(context.Context, *SearchOutboundResourceDisplayRequest) (*ListOutboundResourceDisplay, error)
	// ResourceDisplay item
	ReadOutboundResourceDisplay(context.Context, *ReadOutboundResourceDisplayRequest) (*ResourceDisplay, error)
	// Update ResourceDisplay
	UpdateOutboundResourceDisplay(context.Context, *UpdateOutboundResourceDisplayRequest) (*ResourceDisplay, error)
	// Remove ResourceDisplay
	DeleteOutboundResourceDisplay(context.Context, *DeleteOutboundResourceDisplayRequest) (*ResourceDisplay, error)
}

// UnimplementedOutboundResourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOutboundResourceServiceServer struct {
}

func (*UnimplementedOutboundResourceServiceServer) CreateOutboundResource(ctx context.Context, req *CreateOutboundResourceRequest) (*OutboundResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOutboundResource not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) SearchOutboundResource(ctx context.Context, req *SearchOutboundResourceRequest) (*ListOutboundResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchOutboundResource not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) ReadOutboundResource(ctx context.Context, req *ReadOutboundResourceRequest) (*OutboundResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOutboundResource not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) UpdateOutboundResource(ctx context.Context, req *UpdateOutboundResourceRequest) (*OutboundResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOutboundResource not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) PatchOutboundResource(ctx context.Context, req *PatchOutboundResourceRequest) (*OutboundResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchOutboundResource not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) DeleteOutboundResource(ctx context.Context, req *DeleteOutboundResourceRequest) (*OutboundResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOutboundResource not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) CreateOutboundResourceDisplay(ctx context.Context, req *CreateOutboundResourceDisplayRequest) (*ResourceDisplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOutboundResourceDisplay not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) SearchOutboundResourceDisplay(ctx context.Context, req *SearchOutboundResourceDisplayRequest) (*ListOutboundResourceDisplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchOutboundResourceDisplay not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) ReadOutboundResourceDisplay(ctx context.Context, req *ReadOutboundResourceDisplayRequest) (*ResourceDisplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOutboundResourceDisplay not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) UpdateOutboundResourceDisplay(ctx context.Context, req *UpdateOutboundResourceDisplayRequest) (*ResourceDisplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOutboundResourceDisplay not implemented")
}
func (*UnimplementedOutboundResourceServiceServer) DeleteOutboundResourceDisplay(ctx context.Context, req *DeleteOutboundResourceDisplayRequest) (*ResourceDisplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOutboundResourceDisplay not implemented")
}

func RegisterOutboundResourceServiceServer(s *grpc.Server, srv OutboundResourceServiceServer) {
	s.RegisterService(&_OutboundResourceService_serviceDesc, srv)
}

func _OutboundResourceService_CreateOutboundResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOutboundResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).CreateOutboundResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/CreateOutboundResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).CreateOutboundResource(ctx, req.(*CreateOutboundResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_SearchOutboundResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOutboundResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).SearchOutboundResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/SearchOutboundResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).SearchOutboundResource(ctx, req.(*SearchOutboundResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_ReadOutboundResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOutboundResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).ReadOutboundResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/ReadOutboundResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).ReadOutboundResource(ctx, req.(*ReadOutboundResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_UpdateOutboundResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOutboundResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).UpdateOutboundResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/UpdateOutboundResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).UpdateOutboundResource(ctx, req.(*UpdateOutboundResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_PatchOutboundResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOutboundResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).PatchOutboundResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/PatchOutboundResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).PatchOutboundResource(ctx, req.(*PatchOutboundResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_DeleteOutboundResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOutboundResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).DeleteOutboundResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/DeleteOutboundResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).DeleteOutboundResource(ctx, req.(*DeleteOutboundResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_CreateOutboundResourceDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOutboundResourceDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).CreateOutboundResourceDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/CreateOutboundResourceDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).CreateOutboundResourceDisplay(ctx, req.(*CreateOutboundResourceDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_SearchOutboundResourceDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOutboundResourceDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).SearchOutboundResourceDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/SearchOutboundResourceDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).SearchOutboundResourceDisplay(ctx, req.(*SearchOutboundResourceDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_ReadOutboundResourceDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOutboundResourceDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).ReadOutboundResourceDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/ReadOutboundResourceDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).ReadOutboundResourceDisplay(ctx, req.(*ReadOutboundResourceDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_UpdateOutboundResourceDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOutboundResourceDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).UpdateOutboundResourceDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/UpdateOutboundResourceDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).UpdateOutboundResourceDisplay(ctx, req.(*UpdateOutboundResourceDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboundResourceService_DeleteOutboundResourceDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOutboundResourceDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboundResourceServiceServer).DeleteOutboundResourceDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.OutboundResourceService/DeleteOutboundResourceDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboundResourceServiceServer).DeleteOutboundResourceDisplay(ctx, req.(*DeleteOutboundResourceDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OutboundResourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine.OutboundResourceService",
	HandlerType: (*OutboundResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOutboundResource",
			Handler:    _OutboundResourceService_CreateOutboundResource_Handler,
		},
		{
			MethodName: "SearchOutboundResource",
			Handler:    _OutboundResourceService_SearchOutboundResource_Handler,
		},
		{
			MethodName: "ReadOutboundResource",
			Handler:    _OutboundResourceService_ReadOutboundResource_Handler,
		},
		{
			MethodName: "UpdateOutboundResource",
			Handler:    _OutboundResourceService_UpdateOutboundResource_Handler,
		},
		{
			MethodName: "PatchOutboundResource",
			Handler:    _OutboundResourceService_PatchOutboundResource_Handler,
		},
		{
			MethodName: "DeleteOutboundResource",
			Handler:    _OutboundResourceService_DeleteOutboundResource_Handler,
		},
		{
			MethodName: "CreateOutboundResourceDisplay",
			Handler:    _OutboundResourceService_CreateOutboundResourceDisplay_Handler,
		},
		{
			MethodName: "SearchOutboundResourceDisplay",
			Handler:    _OutboundResourceService_SearchOutboundResourceDisplay_Handler,
		},
		{
			MethodName: "ReadOutboundResourceDisplay",
			Handler:    _OutboundResourceService_ReadOutboundResourceDisplay_Handler,
		},
		{
			MethodName: "UpdateOutboundResourceDisplay",
			Handler:    _OutboundResourceService_UpdateOutboundResourceDisplay_Handler,
		},
		{
			MethodName: "DeleteOutboundResourceDisplay",
			Handler:    _OutboundResourceService_DeleteOutboundResourceDisplay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "outbound_resource.proto",
}
