// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/cognitive_profile.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	engine "github.com/webitel/protos/engine"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceType int32

const (
	ServiceType_STT ServiceType = 0
	ServiceType_TTS ServiceType = 1
)

var ServiceType_name = map[int32]string{
	0: "STT",
	1: "TTS",
}

var ServiceType_value = map[string]int32{
	"STT": 0,
	"TTS": 1,
}

func (x ServiceType) String() string {
	return proto.EnumName(ServiceType_name, int32(x))
}

func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{0}
}

type ProviderType int32

const (
	ProviderType_Microsoft ProviderType = 0
)

var ProviderType_name = map[int32]string{
	0: "Microsoft",
}

var ProviderType_value = map[string]int32{
	"Microsoft": 0,
}

func (x ProviderType) String() string {
	return proto.EnumName(ProviderType_name, int32(x))
}

func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{1}
}

type CognitiveProfile struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            int64             `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            *engine.Lookup    `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            int64             `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            *engine.Lookup    `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Provider             ProviderType      `protobuf:"varint,6,opt,name=provider,proto3,enum=storage.ProviderType" json:"provider,omitempty"`
	Properties           map[string]string `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Enabled              bool              `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                 string            `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Description          string            `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Service              ServiceType       `protobuf:"varint,11,opt,name=service,proto3,enum=storage.ServiceType" json:"service,omitempty"`
	Default              bool              `protobuf:"varint,12,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CognitiveProfile) Reset()         { *m = CognitiveProfile{} }
func (m *CognitiveProfile) String() string { return proto.CompactTextString(m) }
func (*CognitiveProfile) ProtoMessage()    {}
func (*CognitiveProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{0}
}

func (m *CognitiveProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CognitiveProfile.Unmarshal(m, b)
}
func (m *CognitiveProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CognitiveProfile.Marshal(b, m, deterministic)
}
func (m *CognitiveProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CognitiveProfile.Merge(m, src)
}
func (m *CognitiveProfile) XXX_Size() int {
	return xxx_messageInfo_CognitiveProfile.Size(m)
}
func (m *CognitiveProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_CognitiveProfile.DiscardUnknown(m)
}

var xxx_messageInfo_CognitiveProfile proto.InternalMessageInfo

func (m *CognitiveProfile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CognitiveProfile) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CognitiveProfile) GetCreatedBy() *engine.Lookup {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *CognitiveProfile) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *CognitiveProfile) GetUpdatedBy() *engine.Lookup {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

func (m *CognitiveProfile) GetProvider() ProviderType {
	if m != nil {
		return m.Provider
	}
	return ProviderType_Microsoft
}

func (m *CognitiveProfile) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *CognitiveProfile) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CognitiveProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CognitiveProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CognitiveProfile) GetService() ServiceType {
	if m != nil {
		return m.Service
	}
	return ServiceType_STT
}

func (m *CognitiveProfile) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type CreateCognitiveProfileRequest struct {
	Provider             ProviderType      `protobuf:"varint,1,opt,name=provider,proto3,enum=storage.ProviderType" json:"provider,omitempty"`
	Properties           map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Enabled              bool              `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                 string            `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string            `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Service              ServiceType       `protobuf:"varint,6,opt,name=service,proto3,enum=storage.ServiceType" json:"service,omitempty"`
	Default              bool              `protobuf:"varint,8,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCognitiveProfileRequest) Reset()         { *m = CreateCognitiveProfileRequest{} }
func (m *CreateCognitiveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCognitiveProfileRequest) ProtoMessage()    {}
func (*CreateCognitiveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{1}
}

func (m *CreateCognitiveProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCognitiveProfileRequest.Unmarshal(m, b)
}
func (m *CreateCognitiveProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCognitiveProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateCognitiveProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCognitiveProfileRequest.Merge(m, src)
}
func (m *CreateCognitiveProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCognitiveProfileRequest.Size(m)
}
func (m *CreateCognitiveProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCognitiveProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCognitiveProfileRequest proto.InternalMessageInfo

func (m *CreateCognitiveProfileRequest) GetProvider() ProviderType {
	if m != nil {
		return m.Provider
	}
	return ProviderType_Microsoft
}

func (m *CreateCognitiveProfileRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *CreateCognitiveProfileRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CreateCognitiveProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCognitiveProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCognitiveProfileRequest) GetService() ServiceType {
	if m != nil {
		return m.Service
	}
	return ServiceType_STT
}

func (m *CreateCognitiveProfileRequest) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type SearchCognitiveProfileRequest struct {
	Page                 int32         `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32         `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string        `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort                 string        `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields               []string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Id                   []int64       `protobuf:"varint,6,rep,packed,name=id,proto3" json:"id,omitempty"`
	Service              []ServiceType `protobuf:"varint,7,rep,packed,name=service,proto3,enum=storage.ServiceType" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SearchCognitiveProfileRequest) Reset()         { *m = SearchCognitiveProfileRequest{} }
func (m *SearchCognitiveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SearchCognitiveProfileRequest) ProtoMessage()    {}
func (*SearchCognitiveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{2}
}

func (m *SearchCognitiveProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCognitiveProfileRequest.Unmarshal(m, b)
}
func (m *SearchCognitiveProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCognitiveProfileRequest.Marshal(b, m, deterministic)
}
func (m *SearchCognitiveProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCognitiveProfileRequest.Merge(m, src)
}
func (m *SearchCognitiveProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SearchCognitiveProfileRequest.Size(m)
}
func (m *SearchCognitiveProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCognitiveProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCognitiveProfileRequest proto.InternalMessageInfo

func (m *SearchCognitiveProfileRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchCognitiveProfileRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchCognitiveProfileRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchCognitiveProfileRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchCognitiveProfileRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SearchCognitiveProfileRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SearchCognitiveProfileRequest) GetService() []ServiceType {
	if m != nil {
		return m.Service
	}
	return nil
}

type ListCognitiveProfile struct {
	Next                 bool                `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*CognitiveProfile `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListCognitiveProfile) Reset()         { *m = ListCognitiveProfile{} }
func (m *ListCognitiveProfile) String() string { return proto.CompactTextString(m) }
func (*ListCognitiveProfile) ProtoMessage()    {}
func (*ListCognitiveProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{3}
}

func (m *ListCognitiveProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCognitiveProfile.Unmarshal(m, b)
}
func (m *ListCognitiveProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCognitiveProfile.Marshal(b, m, deterministic)
}
func (m *ListCognitiveProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCognitiveProfile.Merge(m, src)
}
func (m *ListCognitiveProfile) XXX_Size() int {
	return xxx_messageInfo_ListCognitiveProfile.Size(m)
}
func (m *ListCognitiveProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCognitiveProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ListCognitiveProfile proto.InternalMessageInfo

func (m *ListCognitiveProfile) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListCognitiveProfile) GetItems() []*CognitiveProfile {
	if m != nil {
		return m.Items
	}
	return nil
}

type ReadCognitiveProfileRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCognitiveProfileRequest) Reset()         { *m = ReadCognitiveProfileRequest{} }
func (m *ReadCognitiveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ReadCognitiveProfileRequest) ProtoMessage()    {}
func (*ReadCognitiveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{4}
}

func (m *ReadCognitiveProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCognitiveProfileRequest.Unmarshal(m, b)
}
func (m *ReadCognitiveProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCognitiveProfileRequest.Marshal(b, m, deterministic)
}
func (m *ReadCognitiveProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCognitiveProfileRequest.Merge(m, src)
}
func (m *ReadCognitiveProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ReadCognitiveProfileRequest.Size(m)
}
func (m *ReadCognitiveProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCognitiveProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCognitiveProfileRequest proto.InternalMessageInfo

func (m *ReadCognitiveProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateCognitiveProfileRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider             ProviderType      `protobuf:"varint,2,opt,name=provider,proto3,enum=storage.ProviderType" json:"provider,omitempty"`
	Properties           map[string]string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Enabled              bool              `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                 string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Service              ServiceType       `protobuf:"varint,7,opt,name=service,proto3,enum=storage.ServiceType" json:"service,omitempty"`
	Default              bool              `protobuf:"varint,8,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateCognitiveProfileRequest) Reset()         { *m = UpdateCognitiveProfileRequest{} }
func (m *UpdateCognitiveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCognitiveProfileRequest) ProtoMessage()    {}
func (*UpdateCognitiveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{5}
}

func (m *UpdateCognitiveProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCognitiveProfileRequest.Unmarshal(m, b)
}
func (m *UpdateCognitiveProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCognitiveProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCognitiveProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCognitiveProfileRequest.Merge(m, src)
}
func (m *UpdateCognitiveProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCognitiveProfileRequest.Size(m)
}
func (m *UpdateCognitiveProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCognitiveProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCognitiveProfileRequest proto.InternalMessageInfo

func (m *UpdateCognitiveProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCognitiveProfileRequest) GetProvider() ProviderType {
	if m != nil {
		return m.Provider
	}
	return ProviderType_Microsoft
}

func (m *UpdateCognitiveProfileRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *UpdateCognitiveProfileRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *UpdateCognitiveProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCognitiveProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateCognitiveProfileRequest) GetService() ServiceType {
	if m != nil {
		return m.Service
	}
	return ServiceType_STT
}

func (m *UpdateCognitiveProfileRequest) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type PatchCognitiveProfileRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider             ProviderType      `protobuf:"varint,2,opt,name=provider,proto3,enum=storage.ProviderType" json:"provider,omitempty"`
	Properties           map[string]string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Enabled              bool              `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                 string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Service              ServiceType       `protobuf:"varint,7,opt,name=service,proto3,enum=storage.ServiceType" json:"service,omitempty"`
	Default              bool              `protobuf:"varint,8,opt,name=default,proto3" json:"default,omitempty"`
	Fields               []string          `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PatchCognitiveProfileRequest) Reset()         { *m = PatchCognitiveProfileRequest{} }
func (m *PatchCognitiveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*PatchCognitiveProfileRequest) ProtoMessage()    {}
func (*PatchCognitiveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{6}
}

func (m *PatchCognitiveProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchCognitiveProfileRequest.Unmarshal(m, b)
}
func (m *PatchCognitiveProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchCognitiveProfileRequest.Marshal(b, m, deterministic)
}
func (m *PatchCognitiveProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchCognitiveProfileRequest.Merge(m, src)
}
func (m *PatchCognitiveProfileRequest) XXX_Size() int {
	return xxx_messageInfo_PatchCognitiveProfileRequest.Size(m)
}
func (m *PatchCognitiveProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchCognitiveProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchCognitiveProfileRequest proto.InternalMessageInfo

func (m *PatchCognitiveProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PatchCognitiveProfileRequest) GetProvider() ProviderType {
	if m != nil {
		return m.Provider
	}
	return ProviderType_Microsoft
}

func (m *PatchCognitiveProfileRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *PatchCognitiveProfileRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *PatchCognitiveProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PatchCognitiveProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PatchCognitiveProfileRequest) GetService() ServiceType {
	if m != nil {
		return m.Service
	}
	return ServiceType_STT
}

func (m *PatchCognitiveProfileRequest) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *PatchCognitiveProfileRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeleteCognitiveProfileRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCognitiveProfileRequest) Reset()         { *m = DeleteCognitiveProfileRequest{} }
func (m *DeleteCognitiveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCognitiveProfileRequest) ProtoMessage()    {}
func (*DeleteCognitiveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f19b675a4c288c, []int{7}
}

func (m *DeleteCognitiveProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCognitiveProfileRequest.Unmarshal(m, b)
}
func (m *DeleteCognitiveProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCognitiveProfileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCognitiveProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCognitiveProfileRequest.Merge(m, src)
}
func (m *DeleteCognitiveProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCognitiveProfileRequest.Size(m)
}
func (m *DeleteCognitiveProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCognitiveProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCognitiveProfileRequest proto.InternalMessageInfo

func (m *DeleteCognitiveProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("storage.ServiceType", ServiceType_name, ServiceType_value)
	proto.RegisterEnum("storage.ProviderType", ProviderType_name, ProviderType_value)
	proto.RegisterType((*CognitiveProfile)(nil), "storage.CognitiveProfile")
	proto.RegisterMapType((map[string]string)(nil), "storage.CognitiveProfile.PropertiesEntry")
	proto.RegisterType((*CreateCognitiveProfileRequest)(nil), "storage.CreateCognitiveProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "storage.CreateCognitiveProfileRequest.PropertiesEntry")
	proto.RegisterType((*SearchCognitiveProfileRequest)(nil), "storage.SearchCognitiveProfileRequest")
	proto.RegisterType((*ListCognitiveProfile)(nil), "storage.ListCognitiveProfile")
	proto.RegisterType((*ReadCognitiveProfileRequest)(nil), "storage.ReadCognitiveProfileRequest")
	proto.RegisterType((*UpdateCognitiveProfileRequest)(nil), "storage.UpdateCognitiveProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "storage.UpdateCognitiveProfileRequest.PropertiesEntry")
	proto.RegisterType((*PatchCognitiveProfileRequest)(nil), "storage.PatchCognitiveProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "storage.PatchCognitiveProfileRequest.PropertiesEntry")
	proto.RegisterType((*DeleteCognitiveProfileRequest)(nil), "storage.DeleteCognitiveProfileRequest")
}

func init() { proto.RegisterFile("storage/cognitive_profile.proto", fileDescriptor_d5f19b675a4c288c) }

var fileDescriptor_d5f19b675a4c288c = []byte{
	// 962 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x8e, 0xdb, 0x44,
	0x18, 0xed, 0xc4, 0xf9, 0x59, 0x7f, 0x59, 0x96, 0x68, 0xb4, 0x0d, 0x26, 0x6d, 0xd4, 0xc1, 0x65,
	0xab, 0x10, 0xd8, 0x58, 0x04, 0x15, 0xa1, 0x95, 0xb8, 0xe8, 0x16, 0x2e, 0x90, 0x8a, 0xb4, 0x72,
	0x52, 0x2e, 0xe0, 0xa2, 0x72, 0xe2, 0x89, 0x3b, 0x6a, 0xd6, 0xe3, 0x1d, 0x4f, 0xb6, 0x04, 0xc4,
	0x05, 0xff, 0x88, 0x0b, 0x2e, 0x28, 0x3c, 0x04, 0x8f, 0xc1, 0x0d, 0x0f, 0xb0, 0xbc, 0x02, 0x0f,
	0x82, 0x3c, 0xb6, 0xb3, 0xde, 0xd4, 0xf1, 0x1a, 0xa8, 0x84, 0x7a, 0x95, 0xf9, 0xf9, 0x66, 0xe6,
	0xcc, 0x39, 0x73, 0x8e, 0x77, 0xe1, 0x46, 0x28, 0xb9, 0x70, 0x3c, 0x6a, 0x4d, 0xb9, 0xe7, 0x33,
	0xc9, 0x4e, 0xe9, 0x83, 0x40, 0xf0, 0x19, 0x9b, 0xd3, 0x41, 0x20, 0xb8, 0xe4, 0xb8, 0x91, 0x14,
	0x74, 0x30, 0xf5, 0x3d, 0xe6, 0x47, 0x85, 0x7e, 0x28, 0xe3, 0xc9, 0xce, 0x75, 0x8f, 0x73, 0x6f,
	0x4e, 0x2d, 0x27, 0x60, 0x96, 0xe3, 0xfb, 0x5c, 0x3a, 0x92, 0x71, 0x3f, 0x4c, 0x66, 0xdf, 0x50,
	0x3f, 0xd3, 0x7d, 0x8f, 0xfa, 0xfb, 0xe1, 0x63, 0xc7, 0xf3, 0xa8, 0xb0, 0x78, 0xa0, 0x2a, 0x9e,
	0xae, 0x36, 0x7f, 0xad, 0x42, 0xeb, 0x6e, 0x0a, 0xe2, 0x28, 0xc6, 0x80, 0x77, 0xa0, 0xc2, 0x5c,
	0x03, 0x11, 0xd4, 0xd3, 0xec, 0x0a, 0x73, 0x71, 0x17, 0x60, 0x2a, 0xa8, 0x23, 0xa9, 0xfb, 0xc0,
	0x91, 0x46, 0x45, 0x8d, 0xeb, 0xc9, 0xc8, 0x1d, 0x89, 0xf7, 0xcf, 0xa7, 0x27, 0x4b, 0x43, 0x23,
	0xa8, 0xd7, 0x1c, 0xee, 0x0c, 0x62, 0xe0, 0x83, 0x7b, 0x9c, 0x3f, 0x5a, 0x04, 0xab, 0xf2, 0xc3,
	0x65, 0xb4, 0xdb, 0x22, 0x70, 0xd3, 0xdd, 0xaa, 0xf1, 0x6e, 0xc9, 0x48, 0xbc, 0x5b, 0x3a, 0x3d,
	0x59, 0x1a, 0xb5, 0xfc, 0xdd, 0x92, 0x8a, 0xc3, 0x25, 0x7e, 0x13, 0xb6, 0x02, 0xc1, 0x4f, 0x99,
	0x4b, 0x85, 0x51, 0x27, 0xa8, 0xb7, 0x33, 0xbc, 0x3a, 0x48, 0xc8, 0x1b, 0x1c, 0x25, 0x13, 0xe3,
	0x65, 0x40, 0xed, 0x55, 0x19, 0xfe, 0x00, 0x20, 0x10, 0x3c, 0xa0, 0x42, 0x32, 0x1a, 0x1a, 0x0d,
	0xa2, 0xf5, 0x9a, 0xc3, 0xd7, 0x56, 0x8b, 0xd6, 0xd9, 0x88, 0x76, 0x49, 0x6a, 0xdf, 0xf7, 0xa5,
	0x58, 0xda, 0x99, 0xc5, 0xd8, 0x80, 0x06, 0xf5, 0x9d, 0xc9, 0x9c, 0xba, 0xc6, 0x16, 0x41, 0xbd,
	0x2d, 0x3b, 0xed, 0x62, 0x0c, 0x55, 0xdf, 0x39, 0xa6, 0x86, 0x4e, 0x50, 0x4f, 0xb7, 0x55, 0x1b,
	0x13, 0x68, 0xba, 0x34, 0x9c, 0x0a, 0xa6, 0xe4, 0x30, 0x40, 0x4d, 0x65, 0x87, 0xf0, 0x00, 0x1a,
	0x21, 0x15, 0xa7, 0x6c, 0x4a, 0x8d, 0xa6, 0xba, 0xcc, 0xee, 0x0a, 0xd7, 0x28, 0x1e, 0x57, 0x77,
	0x49, 0x8b, 0xa2, 0xf3, 0x5d, 0x3a, 0x73, 0x16, 0x73, 0x69, 0x6c, 0xc7, 0xe7, 0x27, 0xdd, 0xce,
	0xbb, 0xf0, 0xe2, 0x1a, 0x70, 0xdc, 0x02, 0xed, 0x11, 0x5d, 0x2a, 0x5d, 0x75, 0x3b, 0x6a, 0xe2,
	0x5d, 0xa8, 0x9d, 0x3a, 0xf3, 0x05, 0x55, 0x9a, 0xea, 0x76, 0xdc, 0x39, 0xa8, 0xbc, 0x83, 0xcc,
	0x5f, 0xaa, 0xd0, 0xbd, 0xab, 0x24, 0x5b, 0xe7, 0xc3, 0xa6, 0x27, 0x0b, 0x1a, 0xca, 0x0b, 0xc4,
	0xa3, 0x72, 0xc4, 0x7f, 0x74, 0x81, 0xf8, 0x8a, 0x22, 0xfe, 0xed, 0x73, 0xe2, 0x8b, 0x8e, 0x2b,
	0xab, 0x82, 0x96, 0xaf, 0x42, 0x75, 0xb3, 0x0a, 0xb5, 0x42, 0x15, 0xea, 0xff, 0x50, 0x85, 0xad,
	0x67, 0xa9, 0xc2, 0xc1, 0x4f, 0xe8, 0xe7, 0x3b, 0x3f, 0x22, 0xf8, 0x1e, 0xf5, 0xf7, 0x62, 0x76,
	0xc8, 0x2a, 0x30, 0x48, 0x12, 0x18, 0x44, 0xc4, 0x04, 0x91, 0x09, 0x77, 0x97, 0xc3, 0xdb, 0xa5,
	0xca, 0xc8, 0x8c, 0x0b, 0x32, 0x1e, 0x8f, 0x88, 0xe3, 0xbb, 0xd1, 0xef, 0x19, 0x52, 0xcc, 0x9c,
	0xa1, 0x95, 0x54, 0x67, 0x28, 0xbd, 0xdc, 0x19, 0xca, 0x30, 0x6d, 0xfe, 0x8e, 0xa0, 0x3b, 0xa2,
	0x8e, 0x98, 0x3e, 0xdc, 0xf4, 0x2c, 0x30, 0x54, 0x03, 0xc7, 0xa3, 0xea, 0x7e, 0x35, 0x5b, 0xb5,
	0xa3, 0xb1, 0x90, 0x7d, 0x16, 0xdf, 0xaf, 0x66, 0xab, 0x36, 0xde, 0x06, 0x74, 0xa2, 0xd4, 0xd2,
	0x6d, 0x74, 0xa2, 0x2a, 0xb8, 0x90, 0xa9, 0x4e, 0x51, 0x1b, 0xb7, 0xa1, 0x3e, 0x63, 0x74, 0xee,
	0x86, 0x46, 0x8d, 0x68, 0x3d, 0xdd, 0x4e, 0x7a, 0x49, 0x3a, 0xd5, 0x89, 0x96, 0xa4, 0x53, 0x46,
	0xad, 0xc8, 0xcb, 0x97, 0xa9, 0x65, 0x7e, 0x02, 0xbb, 0xf7, 0x58, 0x28, 0x9f, 0x4a, 0xbd, 0xe8,
	0xad, 0xd0, 0x4f, 0xa5, 0x42, 0xbe, 0x65, 0xab, 0x36, 0xb6, 0xa0, 0xc6, 0x24, 0x3d, 0x4e, 0x1f,
	0xeb, 0xcb, 0x1b, 0x53, 0xc2, 0x8e, 0xeb, 0xcc, 0x7d, 0xb8, 0x66, 0x53, 0xc7, 0xdd, 0xc4, 0xce,
	0x5a, 0xb2, 0x9a, 0x4f, 0x34, 0xe8, 0xde, 0x57, 0x59, 0x56, 0x72, 0xc5, 0x05, 0xdb, 0x55, 0xfe,
	0x8d, 0xed, 0xb4, 0x35, 0xdb, 0x15, 0x1e, 0x5f, 0xd6, 0x76, 0xd5, 0x7c, 0xdb, 0xd5, 0x36, 0xdb,
	0xae, 0x5e, 0x68, 0xbb, 0xc6, 0xff, 0x69, 0x3b, 0xf3, 0x37, 0x0d, 0xae, 0x1f, 0x39, 0x72, 0xf3,
	0x23, 0x7f, 0x06, 0xa2, 0xdc, 0xcf, 0x11, 0xe5, 0xf6, 0xf9, 0xa2, 0x82, 0xd3, 0x9f, 0x4f, 0x4d,
	0x32, 0x76, 0xd6, 0xb3, 0x76, 0xfe, 0xaf, 0x5a, 0x59, 0xd0, 0x7d, 0x8f, 0xce, 0x69, 0x69, 0x03,
	0xf5, 0x6f, 0x40, 0x33, 0x83, 0x1c, 0x37, 0x40, 0x1b, 0x8d, 0xc7, 0xad, 0x2b, 0x51, 0x63, 0x3c,
	0x1e, 0xb5, 0x50, 0xbf, 0x0b, 0xdb, 0x59, 0xcd, 0xf0, 0x0b, 0xa0, 0x7f, 0xc8, 0xa6, 0x82, 0x87,
	0x7c, 0x26, 0x5b, 0x57, 0x86, 0x7f, 0xd4, 0xe1, 0xa5, 0xf5, 0xb3, 0x92, 0x0d, 0xf1, 0xd7, 0x08,
	0xda, 0xf9, 0x9f, 0x31, 0x7c, 0xab, 0xdc, 0x77, 0xae, 0xb3, 0x39, 0x62, 0xcc, 0x5b, 0x5f, 0xfd,
	0xf9, 0xd7, 0x93, 0x0a, 0x31, 0xaf, 0x59, 0x1b, 0xff, 0x7c, 0x0c, 0x0f, 0x50, 0x1f, 0x7f, 0x83,
	0xa0, 0x9d, 0x1f, 0xd2, 0x19, 0x14, 0x85, 0x29, 0xde, 0xe9, 0xae, 0xea, 0xf2, 0xa2, 0xd2, 0xbc,
	0xa9, 0x90, 0x74, 0x71, 0x11, 0x12, 0xfc, 0x25, 0x82, 0xdd, 0xbc, 0x2c, 0xc4, 0xaf, 0xae, 0x36,
	0x2f, 0x88, 0xca, 0x22, 0x22, 0x7a, 0xea, 0x78, 0x13, 0x93, 0x82, 0xe3, 0xad, 0xcf, 0x99, 0xfb,
	0x05, 0xfe, 0x01, 0x41, 0x3b, 0x3f, 0xe0, 0x32, 0x54, 0x14, 0x26, 0x60, 0x11, 0x8e, 0xd7, 0x15,
	0x8e, 0xbd, 0xce, 0xa5, 0x38, 0x22, 0x55, 0xbe, 0x43, 0x70, 0x35, 0xd7, 0xd6, 0x78, 0xaf, 0x94,
	0xed, 0x4b, 0x00, 0x19, 0x96, 0x02, 0xf2, 0x2d, 0x82, 0x76, 0xbe, 0x65, 0x32, 0x9c, 0x14, 0x7a,
	0xaa, 0x84, 0x36, 0xfd, 0x4b, 0xa1, 0x1c, 0xde, 0xfc, 0xf8, 0x15, 0x8f, 0xc9, 0x87, 0x8b, 0xc9,
	0x60, 0xca, 0x8f, 0xad, 0xc7, 0x74, 0xc2, 0x24, 0x9d, 0x5b, 0xea, 0xdf, 0x92, 0x30, 0x5d, 0x3c,
	0xa9, 0xab, 0xfe, 0x5b, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xce, 0xa4, 0xfc, 0xfd, 0x32, 0x0d,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CognitiveProfileServiceClient is the client API for CognitiveProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CognitiveProfileServiceClient interface {
	CreateCognitiveProfile(ctx context.Context, in *CreateCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error)
	SearchCognitiveProfile(ctx context.Context, in *SearchCognitiveProfileRequest, opts ...grpc.CallOption) (*ListCognitiveProfile, error)
	ReadCognitiveProfile(ctx context.Context, in *ReadCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error)
	UpdateCognitiveProfile(ctx context.Context, in *UpdateCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error)
	PatchCognitiveProfile(ctx context.Context, in *PatchCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error)
	// Remove BackendProfile
	DeleteCognitiveProfile(ctx context.Context, in *DeleteCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error)
}

type cognitiveProfileServiceClient struct {
	cc *grpc.ClientConn
}

func NewCognitiveProfileServiceClient(cc *grpc.ClientConn) CognitiveProfileServiceClient {
	return &cognitiveProfileServiceClient{cc}
}

func (c *cognitiveProfileServiceClient) CreateCognitiveProfile(ctx context.Context, in *CreateCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error) {
	out := new(CognitiveProfile)
	err := c.cc.Invoke(ctx, "/storage.CognitiveProfileService/CreateCognitiveProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveProfileServiceClient) SearchCognitiveProfile(ctx context.Context, in *SearchCognitiveProfileRequest, opts ...grpc.CallOption) (*ListCognitiveProfile, error) {
	out := new(ListCognitiveProfile)
	err := c.cc.Invoke(ctx, "/storage.CognitiveProfileService/SearchCognitiveProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveProfileServiceClient) ReadCognitiveProfile(ctx context.Context, in *ReadCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error) {
	out := new(CognitiveProfile)
	err := c.cc.Invoke(ctx, "/storage.CognitiveProfileService/ReadCognitiveProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveProfileServiceClient) UpdateCognitiveProfile(ctx context.Context, in *UpdateCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error) {
	out := new(CognitiveProfile)
	err := c.cc.Invoke(ctx, "/storage.CognitiveProfileService/UpdateCognitiveProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveProfileServiceClient) PatchCognitiveProfile(ctx context.Context, in *PatchCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error) {
	out := new(CognitiveProfile)
	err := c.cc.Invoke(ctx, "/storage.CognitiveProfileService/PatchCognitiveProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveProfileServiceClient) DeleteCognitiveProfile(ctx context.Context, in *DeleteCognitiveProfileRequest, opts ...grpc.CallOption) (*CognitiveProfile, error) {
	out := new(CognitiveProfile)
	err := c.cc.Invoke(ctx, "/storage.CognitiveProfileService/DeleteCognitiveProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CognitiveProfileServiceServer is the server API for CognitiveProfileService service.
type CognitiveProfileServiceServer interface {
	CreateCognitiveProfile(context.Context, *CreateCognitiveProfileRequest) (*CognitiveProfile, error)
	SearchCognitiveProfile(context.Context, *SearchCognitiveProfileRequest) (*ListCognitiveProfile, error)
	ReadCognitiveProfile(context.Context, *ReadCognitiveProfileRequest) (*CognitiveProfile, error)
	UpdateCognitiveProfile(context.Context, *UpdateCognitiveProfileRequest) (*CognitiveProfile, error)
	PatchCognitiveProfile(context.Context, *PatchCognitiveProfileRequest) (*CognitiveProfile, error)
	// Remove BackendProfile
	DeleteCognitiveProfile(context.Context, *DeleteCognitiveProfileRequest) (*CognitiveProfile, error)
}

// UnimplementedCognitiveProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCognitiveProfileServiceServer struct {
}

func (*UnimplementedCognitiveProfileServiceServer) CreateCognitiveProfile(ctx context.Context, req *CreateCognitiveProfileRequest) (*CognitiveProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCognitiveProfile not implemented")
}
func (*UnimplementedCognitiveProfileServiceServer) SearchCognitiveProfile(ctx context.Context, req *SearchCognitiveProfileRequest) (*ListCognitiveProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCognitiveProfile not implemented")
}
func (*UnimplementedCognitiveProfileServiceServer) ReadCognitiveProfile(ctx context.Context, req *ReadCognitiveProfileRequest) (*CognitiveProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCognitiveProfile not implemented")
}
func (*UnimplementedCognitiveProfileServiceServer) UpdateCognitiveProfile(ctx context.Context, req *UpdateCognitiveProfileRequest) (*CognitiveProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCognitiveProfile not implemented")
}
func (*UnimplementedCognitiveProfileServiceServer) PatchCognitiveProfile(ctx context.Context, req *PatchCognitiveProfileRequest) (*CognitiveProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchCognitiveProfile not implemented")
}
func (*UnimplementedCognitiveProfileServiceServer) DeleteCognitiveProfile(ctx context.Context, req *DeleteCognitiveProfileRequest) (*CognitiveProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCognitiveProfile not implemented")
}

func RegisterCognitiveProfileServiceServer(s *grpc.Server, srv CognitiveProfileServiceServer) {
	s.RegisterService(&_CognitiveProfileService_serviceDesc, srv)
}

func _CognitiveProfileService_CreateCognitiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCognitiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveProfileServiceServer).CreateCognitiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.CognitiveProfileService/CreateCognitiveProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveProfileServiceServer).CreateCognitiveProfile(ctx, req.(*CreateCognitiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveProfileService_SearchCognitiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCognitiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveProfileServiceServer).SearchCognitiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.CognitiveProfileService/SearchCognitiveProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveProfileServiceServer).SearchCognitiveProfile(ctx, req.(*SearchCognitiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveProfileService_ReadCognitiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCognitiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveProfileServiceServer).ReadCognitiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.CognitiveProfileService/ReadCognitiveProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveProfileServiceServer).ReadCognitiveProfile(ctx, req.(*ReadCognitiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveProfileService_UpdateCognitiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCognitiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveProfileServiceServer).UpdateCognitiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.CognitiveProfileService/UpdateCognitiveProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveProfileServiceServer).UpdateCognitiveProfile(ctx, req.(*UpdateCognitiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveProfileService_PatchCognitiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchCognitiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveProfileServiceServer).PatchCognitiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.CognitiveProfileService/PatchCognitiveProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveProfileServiceServer).PatchCognitiveProfile(ctx, req.(*PatchCognitiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveProfileService_DeleteCognitiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCognitiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveProfileServiceServer).DeleteCognitiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.CognitiveProfileService/DeleteCognitiveProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveProfileServiceServer).DeleteCognitiveProfile(ctx, req.(*DeleteCognitiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CognitiveProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.CognitiveProfileService",
	HandlerType: (*CognitiveProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCognitiveProfile",
			Handler:    _CognitiveProfileService_CreateCognitiveProfile_Handler,
		},
		{
			MethodName: "SearchCognitiveProfile",
			Handler:    _CognitiveProfileService_SearchCognitiveProfile_Handler,
		},
		{
			MethodName: "ReadCognitiveProfile",
			Handler:    _CognitiveProfileService_ReadCognitiveProfile_Handler,
		},
		{
			MethodName: "UpdateCognitiveProfile",
			Handler:    _CognitiveProfileService_UpdateCognitiveProfile_Handler,
		},
		{
			MethodName: "PatchCognitiveProfile",
			Handler:    _CognitiveProfileService_PatchCognitiveProfile_Handler,
		},
		{
			MethodName: "DeleteCognitiveProfile",
			Handler:    _CognitiveProfileService_DeleteCognitiveProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/cognitive_profile.proto",
}
