name: Buf

on:
  push:
    branches: [ main ]
    paths:
      - "**.proto"
      - "**/buf.yaml"
      - "**/buf.lock"
      - "**/buf.md"
      - "**/README.md"
      - "**/LICENSE"
      - ".github/workflows/buf-push.yml"

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect:
    name: Detect changed modules
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changed modules
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cases:          'cases/**'
            cc:             'cc/**'
            chat:           'chat/**'
            engine:         'engine/**'
            fs:             'fs/**'
            general:        'general/**'
            logger:         'logger/**'
            media-exporter: 'media-exporter/**'
            storage:        'storage/**'
            webitel-go:     'webitel-go/**'
            workflow:       'workflow/**'

  push:
    name: Push to BSR
    needs: detect
    if: needs.detect.outputs.modules != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        inputs: ${{ fromJSON(needs.detect.outputs.modules) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push modules
        uses: bufbuild/buf-action@v1
        with:
          version: "1.57.2"
          token: ${{ secrets.BUF_TOKEN }}
          input: ${{ matrix.inputs }}
          push: true
