name: buf-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "logger"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "chat"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "engine"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "storage"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "cc"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "workflow"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "fs"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "webitel-go"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "general"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "cases"
          buf_token: ${{ secrets.BUF_TOKEN }}