on:
  push:
    paths:
      - logger/**

jobs:
  swagger-mix:
    runs-on: ubuntu-latest
    name: Run protoc gen-swagger compiler on logger
    steps:
        - name: Checkout the code
          uses: actions/checkout@v4
        - name: Install protoc
          run: sudo apt-get install -y protobuf-compiler
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.22
        - name: Instal protoc-gen-swagger
          run: go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@latest
        - name: Run compiler
          run:  protoc -I./annotations -I./general/general.proto -I./logger -I. --swagger_out=version=false,json_names_for_fields=false,allow_delete_body=true,include_package_in_tags=false,allow_repeated_fields_in_body=false,fqn_for_swagger_name=false,merge_file_name=logger,allow_merge=true:./swagger ./logger/*.proto
        - name: Run swagger-mix
          run: go run github.com/msample/swagger-mixin@latest swagger/engine.swagger.json swagger/storage.swagger.json swagger/messages.swagger.json swagger/logger.swagger.json swagger/contacts.swagger.json swagger/webitel-go.swagger.json swagger/wfm.swagger.json  > swagger/api.json
        - name: Push changes
          if: always()
          run: |
              git add swagger/api.json
              git add swagger/logger.swagger.json
              git config --global user.name 'webitel-bot'
              git config --global user.email 'webitel-bot@users.noreply.github.com'
              git commit -am "Automated logger.swagger.json generation"
              git push